-- 创建 moment 表
CREATE TABLE IF NOT EXISTS `moment` (
id INT PRIMARY KEY AUTO_INCREMENT,
conent VARCHAR(1000) NOT NULL,
user_id INT NOT NULL,
createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY(user_id) REFERENCES user(id)
);

-- moment 表插入语句
INSERT INTO moment (user_id, content) VALUES (3, '心之所向，素履以往；生如逆旅，一苇以航');
INSERT INTO moment (user_id, content) VALUES (4, '民胞物与之量，内圣外王之心');

-- 创建 comment 表
CREATE TABLE IF NOT EXISTS comment (
id INT PRIMARY KEY AUTO_INCREMENT,
content VARCHAR(1000) NOT NULL,
moment_id INT NOT NULL,
user_id INT NOT NULL,
comment_id INT DEFAULT NULL,

FOREIGN KEY(moment_id) REFERENCES moment(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(comment_id) REFERENCES comment(id) ON DELETE CASCADE ON UPDATE CASCADE
)